package types

import (
	"testing"

	"github.com/micro-plat/lib4go/ut"
)

type Person struct {
	Name   string
	Age    int
	Emails []string
}

//LoginState 用户信息
type LoginState struct {
	UserID   string `json:"user_id" m2s:"user_id"`
	UserName string `json:"user_name" m2s:"user_name"`
	SystemID int    `json:"sys_id" m2s:"sys_id"`
	RoleID   int    `json:"role_id" m2s:"role_id"`
}

func TestMap2Struct(t *testing.T) {

	// This input can come from anywhere, but typically comes from
	// something like decoding JSON, generated by a weakly typed language
	// such as PHP.
	input := map[string]interface{}{
		"user_id": "123",                    // number => string
		"age":     "42",                     // string => number
		"emails":  map[string]interface{}{}, // empty map => empty array
	}
	var result LoginState
	err := Map2Struct(input, &result)
	if err != nil {
		t.Error(err)
	}
	ut.Expect(t, result.UserID, "123")
}
